// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvjv9tZEFCVvvqXyowPZmsWX3VPT69sE',
    appId: '1:1093560168947:web:9d1fbbd39de5e734f76286',
    messagingSenderId: '1093560168947',
    projectId: 'fasum-app-f55dc',
    authDomain: 'fasum-app-f55dc.firebaseapp.com',
    storageBucket: 'fasum-app-f55dc.firebasestorage.app',
    measurementId: 'G-HRP7RBQZ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvKdQy3pYVE_MSf9DuZG3zrRH6Fw8xA0k',
    appId: '1:1093560168947:android:19af35ebebdbc20af76286',
    messagingSenderId: '1093560168947',
    projectId: 'fasum-app-f55dc',
    storageBucket: 'fasum-app-f55dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNd-zN5U1iTJ_LGH2m9I7DbSUlcgSSdL0',
    appId: '1:1093560168947:ios:0047ce575f83e2c5f76286',
    messagingSenderId: '1093560168947',
    projectId: 'fasum-app-f55dc',
    storageBucket: 'fasum-app-f55dc.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNd-zN5U1iTJ_LGH2m9I7DbSUlcgSSdL0',
    appId: '1:1093560168947:ios:0047ce575f83e2c5f76286',
    messagingSenderId: '1093560168947',
    projectId: 'fasum-app-f55dc',
    storageBucket: 'fasum-app-f55dc.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCvjv9tZEFCVvvqXyowPZmsWX3VPT69sE',
    appId: '1:1093560168947:web:e57bbd954f06d8b3f76286',
    messagingSenderId: '1093560168947',
    projectId: 'fasum-app-f55dc',
    authDomain: 'fasum-app-f55dc.firebaseapp.com',
    storageBucket: 'fasum-app-f55dc.firebasestorage.app',
    measurementId: 'G-8PEKBE0F38',
  );
}
